spring:
  application:
    name: hotelBooking
  datasource:
    url: jdbc:postgresql://localhost:5433/hotel_db
    username: hotel_user
    password: hotel_pass
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jwt:
    secret: 2TZph6zamnPAn2I1O5KlZPongz204LHaAjVBwdIilBx
    expiration: 86400000